### ISSUE TITLE
为什么不直接使用java的socket

### ISSUE THREAD

**Issue by imkarl** [GoBelieveIO/AsyncTCP#1]
为什么不直接使用java的socket？

通过jni实现，需要编译多个平台的so文件，也会增加app的安装包体积。
这么做的目的是什么？是出于哪方面的考虑？

**Comment by richmonkey** [comment]
主要是为了在主线程收发消息

**Comment by imkarl** [comment]
不知道你们可不可以提供一个纯java实现的`AsyncTcp`？

我自己尝试了下用java的sockect来收发数据包，总是会导致数据包不完整。

**Comment by richmonkey** [comment]
除了体积因素，有什么其他必要的理由用纯java吗？

**Comment by imkarl** [comment]
没有。

我的想法是：
- 这里没必要用jni的方式来实现（或者说用jni或java实现差别不大）
- 维护没那么方便，多引入了一种编程语言
- 对app的体积有影响（增加50k~150k左右）
- 引用该库时，还需要根据app支持的cpu平台引入不太的.so文件

**Comment by richmonkey** [comment]
第一点不同意你的观点，我觉得没有线程，编程的体验

**Comment by richmonkey** [comment]
多线程和jni对编程体验的影响我们评估是不一样的。
我们现在不能因为这个理由提供纯java版本的sdk

**Comment by richmonkey** [comment]
但是你自己把asynctcp这个java类换成纯java实现，应该比从头用java来实现这个sdk还是简单很多的。

**Comment by imkarl** [comment]
是的。 我自己实现了个纯java版本的`AsyncTCP`，发数据正常，但是在多次 `close()` \ `connect()`后 收到的数据就不对了。还不确定是哪个环节搞错了
